# Generated by Django 3.1 on 2021-11-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20211115_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(verbose_name='Добавить отзыв:'),
        ),
    ]
